process UPLOAD_TO_ENA {
    label 'process_single'

    conda "${moduleDir}/environment.yml"
    container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
        'https://depot.galaxyproject.org/singularity/ena-webin-cli:8.1.1--hdfd78af_1' :
        'biocontainers/ena-webin-cli:8.1.1--hdfd78af_1' }"

    input:
    tuple path(multi_upload_manifest), path(reads)

    output:
    path("ena_upload.log.txt")               , emit: upload_log
    path("upload_metadata.csv")              , emit: upload_metadata
    path "versions.yml"                      , emit: versions

    when:
    task.ext.when == null || task.ext.when

    script:
    test_flag = params.test_upload ? "--test-upload" : ""
    """
    # Temporary until upload_metadata.csv is generated by the upload_to_ena.py script
    touch upload_metadata.csv

    upload_to_ena.py \\
        --upload-username "${params.upload_username}" \\
        --upload-password "${params.upload_password}" \\
        --multi-upload-manifest ${multi_upload_manifest} \\
        --input-dir . \\
        ${test_flag} \\
        --upload-metadata upload_metadata.csv \\
        2> >(tee -a ena_upload.log.txt >&2)

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        upload_to_ena.py : 0.1.0
        ena-webin-cli : 8.1.1
    END_VERSIONS
    """
}
